// Pagefind loader. Only runs in production because the `pagefind.js`
// artifact is generated by the `pagefind --site .output/public` step
// that runs after `nuxt generate`. During `nuxt dev` it doesn't exist.

export default defineNuxtPlugin(async () => {
  if (!import.meta.env.PROD) return {}

  try {
    // @ts-expect-error — generated artifact, no type
    const pagefind = await import(/* @vite-ignore */ '/pagefind/pagefind.js')
    return { provide: { pagefind } }
  } catch (e) {
    console.warn('[pagefind] not available', e)
    return {}
  }
})
